//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserResistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class dbo_User
    {
        public int UserID { get; set; }
        [Required(ErrorMessage =" This field é necessario")]
        public string Username { get; set; }
        [Required(ErrorMessage = " This field é necessario")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password")]
        [DisplayName("Confirm Password")]


        public String ConfirmPassword { get; set; }

        public Nullable<bool> IsAdmin { get; set; }
    }
}
